version: '3.1'

services:

  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgresql://postgres:007934561cgtfru@localhost:5432/bank?schema=public
      PORT: 3000

    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 007934561cgtfru
      POSTGRES_USER: postgres
      POSTGRES_DB: bank
    ports:
    - "5432:5432"
    